baseurl = "/"
title = "Slow Programmer"
theme = "ghostwriter-master"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Slow Programmer"
    description = "A blog about programming, slowly"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"